/* empty css                      */import{S as m,N as p,A as g}from"./assets/vendor-CXGvF-wQ.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();document.addEventListener("DOMContentLoaded",()=>{const r=document.querySelector(".demo-btn"),o=document.getElementById("gameIframe"),n=document.getElementById("closeIframeBtn");r&&o&&n&&(r.addEventListener("click",s=>{s.preventDefault();const e=r.getAttribute("data-game-url");o.src=e,o.style.display="block",n.style.display="flex"}),n.addEventListener("click",()=>{o.style.display="none",n.style.display="none",o.src=""}))});new m(".my-swiper",{modules:[p,g],slidesPerView:1,spaceBetween:20,centeredSlides:!0,loop:!0,autoplay:{delay:3e3,disableOnInteraction:!1},navigation:{nextEl:".swiper-btn-next",prevEl:".swiper-btn-prev"},breakpoints:{1440:{slidesPerView:2,centeredSlides:!1}}});document.addEventListener("DOMContentLoaded",()=>{const r=document.querySelector(".menu-button"),o=r.querySelector(".icon"),n=document.querySelector(".modal"),s=document.querySelectorAll(".menu-list-item"),e=document.querySelector(".header");let t=!1;const i=`
<svg width="14" height="10" viewBox="0 0 14 10" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M0.5 0.5H13.25M0.5 9.5H13.25M0.5 5H13.25" stroke="#F2F1F2" stroke-linecap="round" />
</svg>
    `,c=`
<svg width="14" height="10" viewBox="0 0 15 15" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M0.500001 0.5L7.25 7.25M7.25 7.25L0.5 14M7.25 7.25L14 14M7.25 7.25L14 0.500001" stroke="#F2F1F2" stroke-linecap="round" stroke-linejoin="round" />
</svg>
    `;r.addEventListener("click",()=>{t=!t,o.innerHTML=t?c:i,t?d():l()}),s.forEach(f=>f.addEventListener("click",()=>{l(),o.innerHTML=i,t=!1})),window.addEventListener("scroll",u);function d(){n.style.display="block"}function l(){n.style.display="none"}function u(){e&&(window.scrollY>60?e.classList.add("header-scroll"):e.classList.remove("header-scroll"))}});document.addEventListener("DOMContentLoaded",()=>{function r(){const n=document.getElementById("site-header");return n?n.offsetHeight:0}function o(n){const s=document.getElementById(n);if(!s)return;const e=r(),t=s.getBoundingClientRect().top+window.pageYOffset-e;window.scrollTo({top:t,behavior:"smooth"})}if(document.querySelectorAll('a[href*="#"]').forEach(n=>{n.addEventListener("click",function(s){const e=this.getAttribute("href");if(!e)return;const[t,i]=e.split("#");if(!i)return;const c=window.location.pathname.split("/").pop();!(t===""||t==="./"||t===c||t==="./"+c)||!document.getElementById(i)||(s.preventDefault(),o(i))})}),window.location.hash){const n=window.location.hash.substring(1);setTimeout(()=>{o(n)},300)}});const a=document.querySelectorAll(".navigation-item");a.forEach(r=>{r.addEventListener("click",()=>{a.forEach(o=>o.classList.remove("is-active")),r.classList.add("is-active")})});
//# sourceMappingURL=index.js.map
